version: "3.8"

# Development environment override
services:
  django:
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./:/srv/app:rw,cached
      # If you develop on Mac you can remove the var/ directory from the bind-mount
      # for better performance by enabling the next line 
      # - /srv/app/var
  react:
    volumes:
      - ./ui:/srv/ui:rw,cached
